variables:
  GIT_SUBMODULE_STRATEGY: recursive

.basic_job:
  image: gcc

  script:
    - mkdir build
    - cd build
    - cmake .. -DFTK_BUILD_TESTS=ON ${CMAKE_ARG}
    - make VERBOSE=1

  after_script: 
    - ctest -VV

  tags:
    - shared_ssh

no-dependencies:
  extends: .basic_job

netcdf:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_NETCDF=ON"

intel-mpich:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_MPI=ON"
    CC: mpicc
    CXX: mpicxx
  before_script:
    - module load mpich/3.4.2-intel
    - module load intel/20.2

intel-mpich-hdf5:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_MPI=ON -DFTK_USE_HDF5=ON -DFTK_HDF5_DIR=/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/hdf5/1.12.1-mpich-3.4.2-intel-parallel-fortran"
    CC: mpicc
    CXX: mpicxx
  before_script:
    - module load hdf5/1.12.1-mpich-3.4.2-intel-parallel-fortran
    - module load mpich/3.4.2-intel
    - module load intel/20.2

cuda-compile-only:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_CUDA=ON"
  before_script:
    - module load cuda/10.2

python3-setup-build-only:
  before_script:
    - module load anaconda3/2020.02
  script:
    - python setup.py build
  tags:
    - shared_ssh

python3:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_BUILD_PYFTK=ON -DFTK_BUILD_EXECUTABLES=OFF"
  before_script:
    - module load anaconda3/2020.02

intel-tbb:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_TBB=ON -DTBB_ROOT=/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/intel/20.2/tbb"
  before_script:
    - module load intel/20.2

intel-mpich-tbb:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_MPI=ON -DFTK_USE_TBB=ON -DTBB_ROOT=/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/intel/20.2/tbb"
    CC: mpicc
    CXX: mpicxx
  before_script:
    - module load mpich/3.4.2-intel
    - module load intel/20.2

# job-vtk:
#   extends: .basic_job
#   variables:
#     CMAKE_ARG: "-DFTK_USE_VTK=ON"
#   before_script:
#     - source /nfs/gce/projects/PEDAL-GCE/hguo/spack/share/spack/setup-env.sh
#     - module load gcc/8.3.0-fjpc5ys
#     - spack load /qqzhye5
