# image: gcc

.basic_job:
  image: gcc

  script:
    - mkdir build
    - cd build
    - cmake .. -DFTK_BUILD_TESTS=ON ${CMAKE_ARG}
    - make VERBOSE=1

  after_script: 
    - ctest -VV

  tags:
    - shared_ssh

job-no-dependencies:
  extends: .basic_job

job-intel-mpich:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_MPI=ON"
    CC: mpicc
    CXX: mpicxx
  before_script:
    - module load mpich/3.4.2-intel
    - module load intel/20.2

job-intel-mpich-hdf5:
  extends: .basic_job
  variables:
    CMAKE_ARG: "-DFTK_USE_MPI=ON -DFTK_USE_HDF5=ON -DFTK_HDF5_DIR=/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/hdf5/1.12.1-mpich-3.4.2-intel-parallel-fortran"
    CC: mpicc
    CXX: mpicxx
  before_script:
    - module load hdf5/1.12.1-mpich-3.4.2-intel-parallel-fortran
    - module load mpich/3.4.2-intel
    - module load intel/20.2

# job-vtk:
#   extends: .basic_job
#   variables:
#     CMAKE_ARG: "-DFTK_USE_VTK=ON"
#   before_script:
#     - source /nfs/gce/projects/PEDAL-GCE/hguo/spack/share/spack/setup-env.sh
#     - module load gcc/8.3.0-fjpc5ys
#     - spack load /qqzhye5
